version: "3.8"

services:
  orchestrator:
    build:
      context: ./orchestrator
    container_name: rust_orchestrator
    depends_on:
      - sub_service_1
      - sub_service_2
      - sub_service_3
    environment:
      - RUST_LOG=info
    networks:
      - app_network
    volumes:
      - ./orchestrator/src/:/app/orchestrator/src/
    command: ./rust_orchestrator 
    ports:
      - 8080:8080

  sub_service_1:
    build:
      context: ./sub_services/sub_service_1
    container_name: sub_service_1
    networks:
      - app_network
    environment:
      - SERVICE_NAME=7_class_prediction_service
    ports:
      - 5001:5001

  sub_service_2:
    build:
      context: ./sub_services/sub_service_2
    container_name: sub_service_2
    networks:
      - app_network
    environment:
      - SERVICE_NAME=lung_segmentation_service
    ports:
      - 5002:5002

  sub_service_3:
    build:
      context: ./sub_services/sub_service_3
    container_name: sub_service_3
    networks:
      - app_network
    environment:
      - SERVICE_NAME=pneumothorax_prediction_service
    ports:
      - 5003:5003

networks:
  app_network:
    driver: bridge